--oracle

CREATE TABLE SA_PESSOA(	CD_PESSOA NUMBER(10,0) NOT NULL ENABLE, CD_FOTO NUMBER(10,0), NM_PESSOA VARCHAR2(250 BYTE) NOT NULL ENABLE, SG_SEXO VARCHAR2(20 BYTE), DT_NASCIMENTO DATE, 
	 CONSTRAINT SA_PESSOA_PK PRIMARY KEY (CD_PESSOA));

CREATE TABLE sa_usuario(cd_user number(10) PRIMARY KEY, NM_senha VARCHAR2(128) NOT NULL,cd_pessoa number(32), NM_LOGIN VARCHAR2(64));
CREATE TABLE sa_grupo(cd_grupo number(10) NOT NULL,ds_grupo varchar2(50), nm_grupo varchar2(150) not null,PRIMARY KEY(cd_grupo));
CREATE TABLE sa_user_grupo(cd_user number(10) not null, cd_grupo number(10) NOT NULL, PRIMARY KEY (cd_user, cd_grupo));
ALTER TABLE sa_user_grupo ADD CONSTRAINT FK_USERID FOREIGN KEY(cd_user) REFERENCES sa_usuario(cd_user);
ALTER TABLE sa_user_grupo ADD CONSTRAINT FK_GRUPOID FOREIGN KEY(cd_GRUPO) REFERENCES sa_GRUPO(cd_GRUPO);
ALTER TABLE sa_usuario ADD CONSTRAINT FK_PessoaID FOREIGN KEY(cd_pessoa) REFERENCES sa_pessoa(cd_pessoa);


 CREATE SEQUENCE  SEQ_PESSOA  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE ;
 CREATE SEQUENCE  SEQ_USUARIO  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE ;
  CREATE SEQUENCE SEQ_GRUPO  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE ;
  
--postgre  
-- CREATE TABLE SA_PESSOA(	CD_PESSOA NUMERIC NOT NULL, CD_FOTO NUMERIC, NM_PESSOA VARCHAR(250) NOT NULL , SG_SEXO VARCHAR(1), DT_NASCIMENTO DATE, 
--	 CONSTRAINT SA_PESSOA_PK PRIMARY KEY (CD_PESSOA));

--CREATE TABLE sa_usuario(cd_user NUMERIC PRIMARY KEY, NM_senha VARCHAR(128) NOT NULL,cd_pessoa numeric, NM_LOGIN VARCHAR(64));
--CREATE TABLE sa_grupo(cd_grupo numeric NOT NULL,ds_grupo varchar(50), nm_grupo varchar(150) not null,PRIMARY KEY(cd_grupo));
--CREATE TABLE sa_user_grupo(cd_user numeric not null, cd_grupo numeric NOT NULL, PRIMARY KEY (cd_user, cd_grupo));
--ALTER TABLE sa_user_grupo ADD CONSTRAINT FK_USERID FOREIGN KEY(cd_user) REFERENCES sa_usuario(cd_user);
--ALTER TABLE sa_user_grupo ADD CONSTRAINT FK_GRUPOID FOREIGN KEY(cd_GRUPO) REFERENCES sa_GRUPO(cd_GRUPO);
--ALTER TABLE sa_usuario ADD CONSTRAINT FK_PessoaID FOREIGN KEY(cd_pessoa) REFERENCES sa_pessoa(cd_pessoa);


-- CREATE SEQUENCE  SEQ_PESSOA  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1   ;
-- CREATE SEQUENCE  SEQ_USUARIO  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 ;
--  CREATE SEQUENCE SEQ_GRUPO  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 ;
  
  
COMMIT;  
  
  
COMMIT;